### PR TITLE
BACKEND Merging Develop into Main

### PR DESCRIPTION
**Pull request by colbyktang**

### CODE REVIEW

**Comment by NPDevelopmentCode** [comment]
We're not getting any coverage information, I'm going to try to apply #81 to see what popsup here.  If it doesn't work, I'll revert it.

**Comment by NPDevelopmentCode** [comment]
With #81 applied, we can see the coverage is 15% (I assume thats because most of the tests are failing).  Do we want to fix the tests first or merge this and fix them later.  I'm fine either way.

**Review by NPDevelopmentCode — APPROVED** [review]

**Comment by devinabreu10** [comment]
> With #81 applied, we can see the coverage is 15% (I assume thats because most of the tests are failing). Do we want to fix the tests first or merge this and fix them later. I'm fine either way.

This code coverage is inaccurate. Me and Franklyn have made a lot of changes to the tests so we should merged those into develop before merging develop into main

**Comment by NPDevelopmentCode** [comment]
> This code coverage is inaccurate. Me and Franklyn have made a lot of changes to the tests so we should merged those into develop before merging develop into main

I fixed 2 issues in #83.  The number reported should accurate if that is applied.

**Comment by colbyktang** [comment]
I swear to god sonarcloud, that UserDTO better not be a code smell

**Comment by colbyktang** [comment]
Please

**Comment by colbyktang** [comment]
I'm watching you SonarCloud

**Comment by colbyktang** [comment]
Ok screw SonarCloud I'm just gonna merge this bad boy

**Pull request merged**
