### PR TITLE
Fixed followers by removing Lombok from Users, Allow JWT Header, Added endpoint to upload multipart file to AWS S3

### PR DESCRIPTION
**Pull request by colbyktang**

### CODE REVIEW

**Comment by NPDevelopmentCode** [comment]
The definition for following needs to be
```
    @JoinTable(name = "followers",
				@JoinColumn(name = "follower_id", referencedColumnName = "id", nullable = false)},
            inverseJoinColumns = {
				@JoinColumn(name = "user_id", referencedColumnName = "id", nullable = false)})
	@ManyToMany(fetch = FetchType.LAZY)
	private Set<User> following;
```

**Comment by NPDevelopmentCode** [comment]
Also, it's not a big deal, but I'd prefer to stick with `follow` for the table and `followed_id` and `follower_id` for the columns.  I thought that was as close to unambiguous as this situation can get.

**Comment by NPDevelopmentCode** [comment]
How did you figure out that Lombok was the issue?  I would have never figured that out.

**Comment by colbyktang** [comment]
> How did you figure out that Lombok was the issue? I would have never figured that out.

I googled it

**Comment by colbyktang** [comment]
> Also, it's not a big deal, but I'd prefer to stick with `follow` for the table and `followed_id` and `follower_id` for the columns. I thought that was as close to unambiguous as this situation can get.

I'll change the table back to follow but I might keep it as user_id and actually change followed_id to target_id since it's easier to discern with tired eyes.

**Review by BarritoN78 — APPROVED** [review]

**Review by devinabreu10 — APPROVED** [review]
Reviewed the changes and nothing seems out of place

**Pull request merged**
